### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  id: ScopeTypeValues
  parent: OpenQA.Selenium.DevTools.V133.Debugger
  children:
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Block
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Catch
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Closure
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Eval
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Global
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Local
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Module
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Script
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.WasmExpressionStack
  - OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.With
  langs:
  - csharp
  - vb
  name: ScopeTypeValues
  nameWithType: ScopeTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ScopeTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated values for Debugger.Scope.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<ScopeTypeValues>))]

      public enum ScopeTypeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of ScopeTypeValues)))>

      Public Enum ScopeTypeValues
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Global
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Global
  id: Global
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Global
  nameWithType: ScopeTypeValues.Global
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Global
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Global
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the global value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "global")]

      Global = 0
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="global")>

      Global = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: global
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Local
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Local
  id: Local
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Local
  nameWithType: ScopeTypeValues.Local
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Local
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Local
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the local value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "local")]

      Local = 1
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="local")>

      Local = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: local
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.With
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.With
  id: With
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: With
  nameWithType: ScopeTypeValues.With
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.With
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: With
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the with value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "with")]

      With = 2
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="with")>

      With = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: with
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Closure
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Closure
  id: Closure
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Closure
  nameWithType: ScopeTypeValues.Closure
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Closure
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Closure
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the closure value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "closure")]

      Closure = 3
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="closure")>

      Closure = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: closure
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Catch
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Catch
  id: Catch
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Catch
  nameWithType: ScopeTypeValues.Catch
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Catch
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Catch
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 38
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the catch value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "catch")]

      Catch = 4
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="catch")>

      Catch = 4
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: catch
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Block
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Block
  id: Block
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Block
  nameWithType: ScopeTypeValues.Block
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Block
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Block
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 43
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the block value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "block")]

      Block = 5
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="block")>

      Block = 5
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: block
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Script
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Script
  id: Script
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Script
  nameWithType: ScopeTypeValues.Script
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Script
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Script
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 48
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the script value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "script")]

      Script = 6
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="script")>

      Script = 6
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: script
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Eval
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Eval
  id: Eval
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Eval
  nameWithType: ScopeTypeValues.Eval
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Eval
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Eval
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 53
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the eval value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "eval")]

      Eval = 7
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="eval")>

      Eval = 7
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: eval
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Module
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Module
  id: Module
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: Module
  nameWithType: ScopeTypeValues.Module
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.Module
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Module
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 58
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the module value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "module")]

      Module = 8
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="module")>

      Module = 8
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: module
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.WasmExpressionStack
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.WasmExpressionStack
  id: WasmExpressionStack
  parent: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  langs:
  - csharp
  - vb
  name: WasmExpressionStack
  nameWithType: ScopeTypeValues.WasmExpressionStack
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.WasmExpressionStack
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: WasmExpressionStack
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/ScopeTypeValues.cs
    startLine: 63
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the wasm-expression-stack value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "wasm-expression-stack")]

      WasmExpressionStack = 9
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
    content.vb: >-
      <EnumMember(Value:="wasm-expression-stack")>

      WasmExpressionStack = 9
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: wasm-expression-stack
references:
- uid: OpenQA.Selenium.DevTools.V133.Debugger
  commentId: N:OpenQA.Selenium.DevTools.V133.Debugger
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V133.Debugger
  nameWithType: OpenQA.Selenium.DevTools.V133.Debugger
  fullName: OpenQA.Selenium.DevTools.V133.Debugger
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Debugger
    name: Debugger
    href: OpenQA.Selenium.DevTools.V133.Debugger.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Debugger
    name: Debugger
    href: OpenQA.Selenium.DevTools.V133.Debugger.html
- uid: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
  parent: OpenQA.Selenium.DevTools.V133.Debugger
  href: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues.html
  name: ScopeTypeValues
  nameWithType: ScopeTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.ScopeTypeValues
