### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings
  id: RemoveDOMBreakpointCommandSettings
  parent: OpenQA.Selenium.DevTools.V133.DOMDebugger
  children:
  - OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName
  - OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId
  - OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type
  langs:
  - csharp
  - vb
  name: RemoveDOMBreakpointCommandSettings
  nameWithType: RemoveDOMBreakpointCommandSettings
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings
  type: Class
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: RemoveDOMBreakpointCommandSettings
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
    startLine: 11
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.DOMDebugger
  summary: RemoveDOMBreakpoint
  example: []
  syntax:
    content: 'public sealed class RemoveDOMBreakpointCommandSettings : ICommand'
    content.vb: Public NotInheritable Class RemoveDOMBreakpointCommandSettings Implements ICommand
  inheritance:
  - System.Object
  implements:
  - OpenQA.Selenium.DevTools.ICommand
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName
  commentId: P:OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName
  id: CommandName
  parent: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings
  langs:
  - csharp
  - vb
  name: CommandName
  nameWithType: RemoveDOMBreakpointCommandSettings.CommandName
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName
  type: Property
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: CommandName
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.DOMDebugger
  summary: Gets the name of the command.
  example: []
  syntax:
    content: >-
      [JsonIgnore]

      public string CommandName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonIgnore>

      Public ReadOnly Property CommandName As String
  overload: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName*
  implements:
  - OpenQA.Selenium.DevTools.ICommand.CommandName
  attributes:
  - type: System.Text.Json.Serialization.JsonIgnoreAttribute
    ctor: System.Text.Json.Serialization.JsonIgnoreAttribute.#ctor
    arguments: []
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId
  commentId: P:OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId
  id: NodeId
  parent: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings
  langs:
  - csharp
  - vb
  name: NodeId
  nameWithType: RemoveDOMBreakpointCommandSettings.NodeId
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId
  type: Property
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: NodeId
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
    startLine: 24
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.DOMDebugger
  summary: Gets or sets the nodeId
  example: []
  syntax:
    content: >-
      [JsonPropertyName("nodeId")]

      public long NodeId { get; set; }
    parameters: []
    return:
      type: System.Int64
    content.vb: >-
      <JsonPropertyName("nodeId")>

      Public Property NodeId As Long
  overload: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: nodeId
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type
  commentId: P:OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type
  id: Type
  parent: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: RemoveDOMBreakpointCommandSettings.Type
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type
  type: Property
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Type
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/DOMDebugger/RemoveDOMBreakpointCommand.cs
    startLine: 31
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.DOMDebugger
  summary: Gets or sets the type
  example: []
  syntax:
    content: >-
      [JsonPropertyName("type")]

      public DOMBreakpointType Type { get; set; }
    parameters: []
    return:
      type: OpenQA.Selenium.DevTools.V133.DOMDebugger.DOMBreakpointType
    content.vb: >-
      <JsonPropertyName("type")>

      Public Property Type As DOMBreakpointType
  overload: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: type
references:
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger
  commentId: N:OpenQA.Selenium.DevTools.V133.DOMDebugger
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V133.DOMDebugger
  nameWithType: OpenQA.Selenium.DevTools.V133.DOMDebugger
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.DOMDebugger
    name: DOMDebugger
    href: OpenQA.Selenium.DevTools.V133.DOMDebugger.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.DOMDebugger
    name: DOMDebugger
    href: OpenQA.Selenium.DevTools.V133.DOMDebugger.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: OpenQA.Selenium.DevTools.ICommand
  commentId: T:OpenQA.Selenium.DevTools.ICommand
  parent: OpenQA.Selenium.DevTools
  href: OpenQA.Selenium.DevTools.ICommand.html
  name: ICommand
  nameWithType: ICommand
  fullName: OpenQA.Selenium.DevTools.ICommand
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenQA.Selenium.DevTools
  commentId: N:OpenQA.Selenium.DevTools
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools
  nameWithType: OpenQA.Selenium.DevTools
  fullName: OpenQA.Selenium.DevTools
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName*
  commentId: Overload:OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName
  href: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.html#OpenQA_Selenium_DevTools_V133_DOMDebugger_RemoveDOMBreakpointCommandSettings_CommandName
  name: CommandName
  nameWithType: RemoveDOMBreakpointCommandSettings.CommandName
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.CommandName
- uid: OpenQA.Selenium.DevTools.ICommand.CommandName
  commentId: P:OpenQA.Selenium.DevTools.ICommand.CommandName
  parent: OpenQA.Selenium.DevTools.ICommand
  href: OpenQA.Selenium.DevTools.ICommand.html#OpenQA_Selenium_DevTools_ICommand_CommandName
  name: CommandName
  nameWithType: ICommand.CommandName
  fullName: OpenQA.Selenium.DevTools.ICommand.CommandName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId*
  commentId: Overload:OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId
  href: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.html#OpenQA_Selenium_DevTools_V133_DOMDebugger_RemoveDOMBreakpointCommandSettings_NodeId
  name: NodeId
  nameWithType: RemoveDOMBreakpointCommandSettings.NodeId
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.NodeId
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type*
  commentId: Overload:OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type
  href: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.html#OpenQA_Selenium_DevTools_V133_DOMDebugger_RemoveDOMBreakpointCommandSettings_Type
  name: Type
  nameWithType: RemoveDOMBreakpointCommandSettings.Type
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.RemoveDOMBreakpointCommandSettings.Type
- uid: OpenQA.Selenium.DevTools.V133.DOMDebugger.DOMBreakpointType
  commentId: T:OpenQA.Selenium.DevTools.V133.DOMDebugger.DOMBreakpointType
  parent: OpenQA.Selenium.DevTools.V133.DOMDebugger
  href: OpenQA.Selenium.DevTools.V133.DOMDebugger.DOMBreakpointType.html
  name: DOMBreakpointType
  nameWithType: DOMBreakpointType
  fullName: OpenQA.Selenium.DevTools.V133.DOMDebugger.DOMBreakpointType
