### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings
  id: OpenUrlCommandSettings
  parent: OpenQA.Selenium.DevTools.V132.FedCm
  children:
  - OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex
  - OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType
  - OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName
  - OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId
  langs:
  - csharp
  - vb
  name: OpenUrlCommandSettings
  nameWithType: OpenUrlCommandSettings
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings
  type: Class
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: OpenUrlCommandSettings
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
    startLine: 11
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.FedCm
  summary: OpenUrl
  example: []
  syntax:
    content: 'public sealed class OpenUrlCommandSettings : ICommand'
    content.vb: Public NotInheritable Class OpenUrlCommandSettings Implements ICommand
  inheritance:
  - System.Object
  implements:
  - OpenQA.Selenium.DevTools.ICommand
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName
  commentId: P:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName
  id: CommandName
  parent: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings
  langs:
  - csharp
  - vb
  name: CommandName
  nameWithType: OpenUrlCommandSettings.CommandName
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName
  type: Property
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: CommandName
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.FedCm
  summary: Gets the name of the command.
  example: []
  syntax:
    content: >-
      [JsonIgnore]

      public string CommandName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonIgnore>

      Public ReadOnly Property CommandName As String
  overload: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName*
  implements:
  - OpenQA.Selenium.DevTools.ICommand.CommandName
  attributes:
  - type: System.Text.Json.Serialization.JsonIgnoreAttribute
    ctor: System.Text.Json.Serialization.JsonIgnoreAttribute.#ctor
    arguments: []
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId
  commentId: P:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId
  id: DialogId
  parent: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings
  langs:
  - csharp
  - vb
  name: DialogId
  nameWithType: OpenUrlCommandSettings.DialogId
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId
  type: Property
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: DialogId
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
    startLine: 24
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.FedCm
  summary: Gets or sets the dialogId
  example: []
  syntax:
    content: >-
      [JsonPropertyName("dialogId")]

      public string DialogId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <JsonPropertyName("dialogId")>

      Public Property DialogId As String
  overload: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: dialogId
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex
  commentId: P:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex
  id: AccountIndex
  parent: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings
  langs:
  - csharp
  - vb
  name: AccountIndex
  nameWithType: OpenUrlCommandSettings.AccountIndex
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex
  type: Property
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: AccountIndex
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
    startLine: 31
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.FedCm
  summary: Gets or sets the accountIndex
  example: []
  syntax:
    content: >-
      [JsonPropertyName("accountIndex")]

      public long AccountIndex { get; set; }
    parameters: []
    return:
      type: System.Int64
    content.vb: >-
      <JsonPropertyName("accountIndex")>

      Public Property AccountIndex As Long
  overload: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: accountIndex
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType
  commentId: P:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType
  id: AccountUrlType
  parent: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings
  langs:
  - csharp
  - vb
  name: AccountUrlType
  nameWithType: OpenUrlCommandSettings.AccountUrlType
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType
  type: Property
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: AccountUrlType
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/FedCm/OpenUrlCommand.cs
    startLine: 38
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.FedCm
  summary: Gets or sets the accountUrlType
  example: []
  syntax:
    content: >-
      [JsonPropertyName("accountUrlType")]

      public AccountUrlType AccountUrlType { get; set; }
    parameters: []
    return:
      type: OpenQA.Selenium.DevTools.V132.FedCm.AccountUrlType
    content.vb: >-
      <JsonPropertyName("accountUrlType")>

      Public Property AccountUrlType As AccountUrlType
  overload: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType*
  attributes:
  - type: System.Text.Json.Serialization.JsonPropertyNameAttribute
    ctor: System.Text.Json.Serialization.JsonPropertyNameAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: accountUrlType
references:
- uid: OpenQA.Selenium.DevTools.V132.FedCm
  commentId: N:OpenQA.Selenium.DevTools.V132.FedCm
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V132.FedCm
  nameWithType: OpenQA.Selenium.DevTools.V132.FedCm
  fullName: OpenQA.Selenium.DevTools.V132.FedCm
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.FedCm
    name: FedCm
    href: OpenQA.Selenium.DevTools.V132.FedCm.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.FedCm
    name: FedCm
    href: OpenQA.Selenium.DevTools.V132.FedCm.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: OpenQA.Selenium.DevTools.ICommand
  commentId: T:OpenQA.Selenium.DevTools.ICommand
  parent: OpenQA.Selenium.DevTools
  href: OpenQA.Selenium.DevTools.ICommand.html
  name: ICommand
  nameWithType: ICommand
  fullName: OpenQA.Selenium.DevTools.ICommand
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: OpenQA.Selenium.DevTools
  commentId: N:OpenQA.Selenium.DevTools
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools
  nameWithType: OpenQA.Selenium.DevTools
  fullName: OpenQA.Selenium.DevTools
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName*
  commentId: Overload:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName
  href: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.html#OpenQA_Selenium_DevTools_V132_FedCm_OpenUrlCommandSettings_CommandName
  name: CommandName
  nameWithType: OpenUrlCommandSettings.CommandName
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.CommandName
- uid: OpenQA.Selenium.DevTools.ICommand.CommandName
  commentId: P:OpenQA.Selenium.DevTools.ICommand.CommandName
  parent: OpenQA.Selenium.DevTools.ICommand
  href: OpenQA.Selenium.DevTools.ICommand.html#OpenQA_Selenium_DevTools_ICommand_CommandName
  name: CommandName
  nameWithType: ICommand.CommandName
  fullName: OpenQA.Selenium.DevTools.ICommand.CommandName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId*
  commentId: Overload:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId
  href: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.html#OpenQA_Selenium_DevTools_V132_FedCm_OpenUrlCommandSettings_DialogId
  name: DialogId
  nameWithType: OpenUrlCommandSettings.DialogId
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.DialogId
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex*
  commentId: Overload:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex
  href: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.html#OpenQA_Selenium_DevTools_V132_FedCm_OpenUrlCommandSettings_AccountIndex
  name: AccountIndex
  nameWithType: OpenUrlCommandSettings.AccountIndex
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountIndex
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType*
  commentId: Overload:OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType
  href: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.html#OpenQA_Selenium_DevTools_V132_FedCm_OpenUrlCommandSettings_AccountUrlType
  name: AccountUrlType
  nameWithType: OpenUrlCommandSettings.AccountUrlType
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.OpenUrlCommandSettings.AccountUrlType
- uid: OpenQA.Selenium.DevTools.V132.FedCm.AccountUrlType
  commentId: T:OpenQA.Selenium.DevTools.V132.FedCm.AccountUrlType
  parent: OpenQA.Selenium.DevTools.V132.FedCm
  href: OpenQA.Selenium.DevTools.V132.FedCm.AccountUrlType.html
  name: AccountUrlType
  nameWithType: AccountUrlType
  fullName: OpenQA.Selenium.DevTools.V132.FedCm.AccountUrlType
