### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  commentId: T:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  id: ViolationSettingNameValues
  parent: OpenQA.Selenium.DevTools.V132.Log
  children:
  - OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedEvent
  - OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedParser
  - OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.DiscouragedAPIUse
  - OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.Handler
  - OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongLayout
  - OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongTask
  - OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.RecurringHandler
  langs:
  - csharp
  - vb
  name: ViolationSettingNameValues
  nameWithType: ViolationSettingNameValues
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ViolationSettingNameValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated values for Log.ViolationSetting.name
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<ViolationSettingNameValues>))]

      public enum ViolationSettingNameValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of ViolationSettingNameValues)))>

      Public Enum ViolationSettingNameValues
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongTask
  commentId: F:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongTask
  id: LongTask
  parent: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  langs:
  - csharp
  - vb
  name: LongTask
  nameWithType: ViolationSettingNameValues.LongTask
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongTask
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: LongTask
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated member for the longTask value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "longTask")]

      LongTask = 0
    return:
      type: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
    content.vb: >-
      <EnumMember(Value:="longTask")>

      LongTask = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: longTask
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongLayout
  commentId: F:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongLayout
  id: LongLayout
  parent: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  langs:
  - csharp
  - vb
  name: LongLayout
  nameWithType: ViolationSettingNameValues.LongLayout
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.LongLayout
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: LongLayout
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated member for the longLayout value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "longLayout")]

      LongLayout = 1
    return:
      type: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
    content.vb: >-
      <EnumMember(Value:="longLayout")>

      LongLayout = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: longLayout
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedEvent
  commentId: F:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedEvent
  id: BlockedEvent
  parent: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  langs:
  - csharp
  - vb
  name: BlockedEvent
  nameWithType: ViolationSettingNameValues.BlockedEvent
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedEvent
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: BlockedEvent
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated member for the blockedEvent value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "blockedEvent")]

      BlockedEvent = 2
    return:
      type: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
    content.vb: >-
      <EnumMember(Value:="blockedEvent")>

      BlockedEvent = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: blockedEvent
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedParser
  commentId: F:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedParser
  id: BlockedParser
  parent: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  langs:
  - csharp
  - vb
  name: BlockedParser
  nameWithType: ViolationSettingNameValues.BlockedParser
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.BlockedParser
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: BlockedParser
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated member for the blockedParser value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "blockedParser")]

      BlockedParser = 3
    return:
      type: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
    content.vb: >-
      <EnumMember(Value:="blockedParser")>

      BlockedParser = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: blockedParser
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.DiscouragedAPIUse
  commentId: F:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.DiscouragedAPIUse
  id: DiscouragedAPIUse
  parent: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  langs:
  - csharp
  - vb
  name: DiscouragedAPIUse
  nameWithType: ViolationSettingNameValues.DiscouragedAPIUse
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.DiscouragedAPIUse
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: DiscouragedAPIUse
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 38
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated member for the discouragedAPIUse value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "discouragedAPIUse")]

      DiscouragedAPIUse = 4
    return:
      type: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
    content.vb: >-
      <EnumMember(Value:="discouragedAPIUse")>

      DiscouragedAPIUse = 4
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: discouragedAPIUse
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.Handler
  commentId: F:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.Handler
  id: Handler
  parent: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  langs:
  - csharp
  - vb
  name: Handler
  nameWithType: ViolationSettingNameValues.Handler
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.Handler
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Handler
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 43
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated member for the handler value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "handler")]

      Handler = 5
    return:
      type: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
    content.vb: >-
      <EnumMember(Value:="handler")>

      Handler = 5
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: handler
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.RecurringHandler
  commentId: F:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.RecurringHandler
  id: RecurringHandler
  parent: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  langs:
  - csharp
  - vb
  name: RecurringHandler
  nameWithType: ViolationSettingNameValues.RecurringHandler
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.RecurringHandler
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: RecurringHandler
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Log/ViolationSettingNameValues.cs
    startLine: 48
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Log
  summary: Enumerated member for the recurringHandler value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "recurringHandler")]

      RecurringHandler = 6
    return:
      type: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
    content.vb: >-
      <EnumMember(Value:="recurringHandler")>

      RecurringHandler = 6
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: recurringHandler
references:
- uid: OpenQA.Selenium.DevTools.V132.Log
  commentId: N:OpenQA.Selenium.DevTools.V132.Log
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V132.Log
  nameWithType: OpenQA.Selenium.DevTools.V132.Log
  fullName: OpenQA.Selenium.DevTools.V132.Log
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Log
    name: Log
    href: OpenQA.Selenium.DevTools.V132.Log.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Log
    name: Log
    href: OpenQA.Selenium.DevTools.V132.Log.html
- uid: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  commentId: T:OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
  parent: OpenQA.Selenium.DevTools.V132.Log
  href: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues.html
  name: ViolationSettingNameValues
  nameWithType: ViolationSettingNameValues
  fullName: OpenQA.Selenium.DevTools.V132.Log.ViolationSettingNameValues
