### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  commentId: T:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  id: ConsoleMessageSourceValues
  parent: OpenQA.Selenium.DevTools.V134.Console
  children:
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Appcache
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.ConsoleApi
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Deprecation
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Javascript
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Network
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Other
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Rendering
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Security
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Storage
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Worker
  - OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Xml
  langs:
  - csharp
  - vb
  name: ConsoleMessageSourceValues
  nameWithType: ConsoleMessageSourceValues
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ConsoleMessageSourceValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated values for Console.ConsoleMessage.source
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<ConsoleMessageSourceValues>))]

      public enum ConsoleMessageSourceValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of ConsoleMessageSourceValues)))>

      Public Enum ConsoleMessageSourceValues
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Xml
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Xml
  id: Xml
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Xml
  nameWithType: ConsoleMessageSourceValues.Xml
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Xml
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Xml
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the xml value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "xml")]

      Xml = 0
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="xml")>

      Xml = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: xml
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Javascript
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Javascript
  id: Javascript
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Javascript
  nameWithType: ConsoleMessageSourceValues.Javascript
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Javascript
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Javascript
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the javascript value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "javascript")]

      Javascript = 1
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="javascript")>

      Javascript = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: javascript
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Network
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Network
  id: Network
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Network
  nameWithType: ConsoleMessageSourceValues.Network
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Network
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Network
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the network value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "network")]

      Network = 2
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="network")>

      Network = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: network
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.ConsoleApi
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.ConsoleApi
  id: ConsoleApi
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: ConsoleApi
  nameWithType: ConsoleMessageSourceValues.ConsoleApi
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.ConsoleApi
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ConsoleApi
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the console-api value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "console-api")]

      ConsoleApi = 3
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="console-api")>

      ConsoleApi = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: console-api
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Storage
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Storage
  id: Storage
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Storage
  nameWithType: ConsoleMessageSourceValues.Storage
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Storage
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Storage
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 38
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the storage value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "storage")]

      Storage = 4
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="storage")>

      Storage = 4
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: storage
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Appcache
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Appcache
  id: Appcache
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Appcache
  nameWithType: ConsoleMessageSourceValues.Appcache
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Appcache
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Appcache
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 43
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the appcache value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "appcache")]

      Appcache = 5
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="appcache")>

      Appcache = 5
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: appcache
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Rendering
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Rendering
  id: Rendering
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Rendering
  nameWithType: ConsoleMessageSourceValues.Rendering
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Rendering
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Rendering
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 48
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the rendering value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "rendering")]

      Rendering = 6
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="rendering")>

      Rendering = 6
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: rendering
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Security
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Security
  id: Security
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Security
  nameWithType: ConsoleMessageSourceValues.Security
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Security
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Security
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 53
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the security value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "security")]

      Security = 7
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="security")>

      Security = 7
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: security
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Other
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Other
  id: Other
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Other
  nameWithType: ConsoleMessageSourceValues.Other
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Other
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Other
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 58
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the other value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "other")]

      Other = 8
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="other")>

      Other = 8
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: other
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Deprecation
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Deprecation
  id: Deprecation
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Deprecation
  nameWithType: ConsoleMessageSourceValues.Deprecation
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Deprecation
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Deprecation
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 63
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the deprecation value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "deprecation")]

      Deprecation = 9
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="deprecation")>

      Deprecation = 9
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: deprecation
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Worker
  commentId: F:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Worker
  id: Worker
  parent: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  langs:
  - csharp
  - vb
  name: Worker
  nameWithType: ConsoleMessageSourceValues.Worker
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.Worker
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Worker
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Console/ConsoleMessageSourceValues.cs
    startLine: 68
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Console
  summary: Enumerated member for the worker value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "worker")]

      Worker = 10
    return:
      type: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
    content.vb: >-
      <EnumMember(Value:="worker")>

      Worker = 10
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: worker
references:
- uid: OpenQA.Selenium.DevTools.V134.Console
  commentId: N:OpenQA.Selenium.DevTools.V134.Console
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V134.Console
  nameWithType: OpenQA.Selenium.DevTools.V134.Console
  fullName: OpenQA.Selenium.DevTools.V134.Console
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134
    name: V134
    href: OpenQA.Selenium.DevTools.V134.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134.Console
    name: Console
    href: OpenQA.Selenium.DevTools.V134.Console.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134
    name: V134
    href: OpenQA.Selenium.DevTools.V134.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134.Console
    name: Console
    href: OpenQA.Selenium.DevTools.V134.Console.html
- uid: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  commentId: T:OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
  parent: OpenQA.Selenium.DevTools.V134.Console
  href: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues.html
  name: ConsoleMessageSourceValues
  nameWithType: ConsoleMessageSourceValues
  fullName: OpenQA.Selenium.DevTools.V134.Console.ConsoleMessageSourceValues
