### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  id: KeyTypeValues
  parent: OpenQA.Selenium.DevTools.V133.IndexedDB
  children:
  - OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Array
  - OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Date
  - OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Number
  - OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.String
  langs:
  - csharp
  - vb
  name: KeyTypeValues
  nameWithType: KeyTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: KeyTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.IndexedDB
  summary: Enumerated values for IndexedDB.Key.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<KeyTypeValues>))]

      public enum KeyTypeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of KeyTypeValues)))>

      Public Enum KeyTypeValues
- uid: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Number
  commentId: F:OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Number
  id: Number
  parent: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  langs:
  - csharp
  - vb
  name: Number
  nameWithType: KeyTypeValues.Number
  fullName: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Number
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Number
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.IndexedDB
  summary: Enumerated member for the number value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "number")]

      Number = 0
    return:
      type: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
    content.vb: >-
      <EnumMember(Value:="number")>

      Number = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: number
- uid: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.String
  commentId: F:OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.String
  id: String
  parent: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  langs:
  - csharp
  - vb
  name: String
  nameWithType: KeyTypeValues.String
  fullName: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.String
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: String
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.IndexedDB
  summary: Enumerated member for the string value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "string")]

      String = 1
    return:
      type: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
    content.vb: >-
      <EnumMember(Value:="string")>

      String = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: string
- uid: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Date
  commentId: F:OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Date
  id: Date
  parent: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  langs:
  - csharp
  - vb
  name: Date
  nameWithType: KeyTypeValues.Date
  fullName: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Date
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Date
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.IndexedDB
  summary: Enumerated member for the date value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "date")]

      Date = 2
    return:
      type: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
    content.vb: >-
      <EnumMember(Value:="date")>

      Date = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: date
- uid: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Array
  commentId: F:OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Array
  id: Array
  parent: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  langs:
  - csharp
  - vb
  name: Array
  nameWithType: KeyTypeValues.Array
  fullName: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.Array
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Array
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/IndexedDB/KeyTypeValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.IndexedDB
  summary: Enumerated member for the array value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "array")]

      Array = 3
    return:
      type: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
    content.vb: >-
      <EnumMember(Value:="array")>

      Array = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: array
references:
- uid: OpenQA.Selenium.DevTools.V133.IndexedDB
  commentId: N:OpenQA.Selenium.DevTools.V133.IndexedDB
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V133.IndexedDB
  nameWithType: OpenQA.Selenium.DevTools.V133.IndexedDB
  fullName: OpenQA.Selenium.DevTools.V133.IndexedDB
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.IndexedDB
    name: IndexedDB
    href: OpenQA.Selenium.DevTools.V133.IndexedDB.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.IndexedDB
    name: IndexedDB
    href: OpenQA.Selenium.DevTools.V133.IndexedDB.html
- uid: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
  parent: OpenQA.Selenium.DevTools.V133.IndexedDB
  href: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues.html
  name: KeyTypeValues
  nameWithType: KeyTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.IndexedDB.KeyTypeValues
