### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  id: ConsoleMessageLevelValues
  parent: OpenQA.Selenium.DevTools.V133.Console
  children:
  - OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Debug
  - OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Error
  - OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Info
  - OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Log
  - OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Warning
  langs:
  - csharp
  - vb
  name: ConsoleMessageLevelValues
  nameWithType: ConsoleMessageLevelValues
  fullName: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ConsoleMessageLevelValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Console
  summary: Enumerated values for Console.ConsoleMessage.level
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<ConsoleMessageLevelValues>))]

      public enum ConsoleMessageLevelValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of ConsoleMessageLevelValues)))>

      Public Enum ConsoleMessageLevelValues
- uid: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Log
  commentId: F:OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Log
  id: Log
  parent: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  langs:
  - csharp
  - vb
  name: Log
  nameWithType: ConsoleMessageLevelValues.Log
  fullName: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Log
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Log
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Console
  summary: Enumerated member for the log value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "log")]

      Log = 0
    return:
      type: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
    content.vb: >-
      <EnumMember(Value:="log")>

      Log = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: log
- uid: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Warning
  commentId: F:OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Warning
  id: Warning
  parent: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  langs:
  - csharp
  - vb
  name: Warning
  nameWithType: ConsoleMessageLevelValues.Warning
  fullName: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Warning
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Warning
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Console
  summary: Enumerated member for the warning value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "warning")]

      Warning = 1
    return:
      type: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
    content.vb: >-
      <EnumMember(Value:="warning")>

      Warning = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: warning
- uid: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Error
  commentId: F:OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Error
  id: Error
  parent: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  langs:
  - csharp
  - vb
  name: Error
  nameWithType: ConsoleMessageLevelValues.Error
  fullName: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Error
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Error
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Console
  summary: Enumerated member for the error value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "error")]

      Error = 2
    return:
      type: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
    content.vb: >-
      <EnumMember(Value:="error")>

      Error = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: error
- uid: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Debug
  commentId: F:OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Debug
  id: Debug
  parent: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  langs:
  - csharp
  - vb
  name: Debug
  nameWithType: ConsoleMessageLevelValues.Debug
  fullName: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Debug
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Debug
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Console
  summary: Enumerated member for the debug value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "debug")]

      Debug = 3
    return:
      type: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
    content.vb: >-
      <EnumMember(Value:="debug")>

      Debug = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: debug
- uid: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Info
  commentId: F:OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Info
  id: Info
  parent: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  langs:
  - csharp
  - vb
  name: Info
  nameWithType: ConsoleMessageLevelValues.Info
  fullName: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.Info
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Info
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Console/ConsoleMessageLevelValues.cs
    startLine: 38
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Console
  summary: Enumerated member for the info value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "info")]

      Info = 4
    return:
      type: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
    content.vb: >-
      <EnumMember(Value:="info")>

      Info = 4
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: info
references:
- uid: OpenQA.Selenium.DevTools.V133.Console
  commentId: N:OpenQA.Selenium.DevTools.V133.Console
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V133.Console
  nameWithType: OpenQA.Selenium.DevTools.V133.Console
  fullName: OpenQA.Selenium.DevTools.V133.Console
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Console
    name: Console
    href: OpenQA.Selenium.DevTools.V133.Console.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Console
    name: Console
    href: OpenQA.Selenium.DevTools.V133.Console.html
- uid: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
  parent: OpenQA.Selenium.DevTools.V133.Console
  href: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues.html
  name: ConsoleMessageLevelValues
  nameWithType: ConsoleMessageLevelValues
  fullName: OpenQA.Selenium.DevTools.V133.Console.ConsoleMessageLevelValues
