### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  id: DebugSymbolsTypeValues
  parent: OpenQA.Selenium.DevTools.V133.Debugger
  children:
  - OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.EmbeddedDWARF
  - OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.ExternalDWARF
  - OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.SourceMap
  langs:
  - csharp
  - vb
  name: DebugSymbolsTypeValues
  nameWithType: DebugSymbolsTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: DebugSymbolsTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated values for Debugger.DebugSymbols.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<DebugSymbolsTypeValues>))]

      public enum DebugSymbolsTypeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of DebugSymbolsTypeValues)))>

      Public Enum DebugSymbolsTypeValues
- uid: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.SourceMap
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.SourceMap
  id: SourceMap
  parent: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  langs:
  - csharp
  - vb
  name: SourceMap
  nameWithType: DebugSymbolsTypeValues.SourceMap
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.SourceMap
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: SourceMap
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the SourceMap value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "SourceMap")]

      SourceMap = 0
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
    content.vb: >-
      <EnumMember(Value:="SourceMap")>

      SourceMap = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: SourceMap
- uid: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.EmbeddedDWARF
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.EmbeddedDWARF
  id: EmbeddedDWARF
  parent: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  langs:
  - csharp
  - vb
  name: EmbeddedDWARF
  nameWithType: DebugSymbolsTypeValues.EmbeddedDWARF
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.EmbeddedDWARF
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: EmbeddedDWARF
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the EmbeddedDWARF value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "EmbeddedDWARF")]

      EmbeddedDWARF = 1
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
    content.vb: >-
      <EnumMember(Value:="EmbeddedDWARF")>

      EmbeddedDWARF = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: EmbeddedDWARF
- uid: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.ExternalDWARF
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.ExternalDWARF
  id: ExternalDWARF
  parent: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  langs:
  - csharp
  - vb
  name: ExternalDWARF
  nameWithType: DebugSymbolsTypeValues.ExternalDWARF
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.ExternalDWARF
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ExternalDWARF
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/DebugSymbolsTypeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the ExternalDWARF value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "ExternalDWARF")]

      ExternalDWARF = 2
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
    content.vb: >-
      <EnumMember(Value:="ExternalDWARF")>

      ExternalDWARF = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: ExternalDWARF
references:
- uid: OpenQA.Selenium.DevTools.V133.Debugger
  commentId: N:OpenQA.Selenium.DevTools.V133.Debugger
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V133.Debugger
  nameWithType: OpenQA.Selenium.DevTools.V133.Debugger
  fullName: OpenQA.Selenium.DevTools.V133.Debugger
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Debugger
    name: Debugger
    href: OpenQA.Selenium.DevTools.V133.Debugger.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Debugger
    name: Debugger
    href: OpenQA.Selenium.DevTools.V133.Debugger.html
- uid: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
  parent: OpenQA.Selenium.DevTools.V133.Debugger
  href: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues.html
  name: DebugSymbolsTypeValues
  nameWithType: DebugSymbolsTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.DebugSymbolsTypeValues
