### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
  id: TrustTokenParamsRefreshPolicyValues
  parent: OpenQA.Selenium.DevTools.V133.Network
  children:
  - OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.Refresh
  - OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.UseCached
  langs:
  - csharp
  - vb
  name: TrustTokenParamsRefreshPolicyValues
  nameWithType: TrustTokenParamsRefreshPolicyValues
  fullName: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Network/TrustTokenParamsRefreshPolicyValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: TrustTokenParamsRefreshPolicyValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Network/TrustTokenParamsRefreshPolicyValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Network
  summary: Enumerated values for Network.TrustTokenParams.refreshPolicy
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<TrustTokenParamsRefreshPolicyValues>))]

      public enum TrustTokenParamsRefreshPolicyValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of TrustTokenParamsRefreshPolicyValues)))>

      Public Enum TrustTokenParamsRefreshPolicyValues
- uid: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.UseCached
  commentId: F:OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.UseCached
  id: UseCached
  parent: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
  langs:
  - csharp
  - vb
  name: UseCached
  nameWithType: TrustTokenParamsRefreshPolicyValues.UseCached
  fullName: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.UseCached
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Network/TrustTokenParamsRefreshPolicyValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: UseCached
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Network/TrustTokenParamsRefreshPolicyValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Network
  summary: Enumerated member for the UseCached value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "UseCached")]

      UseCached = 0
    return:
      type: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
    content.vb: >-
      <EnumMember(Value:="UseCached")>

      UseCached = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: UseCached
- uid: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.Refresh
  commentId: F:OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.Refresh
  id: Refresh
  parent: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
  langs:
  - csharp
  - vb
  name: Refresh
  nameWithType: TrustTokenParamsRefreshPolicyValues.Refresh
  fullName: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.Refresh
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Network/TrustTokenParamsRefreshPolicyValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Refresh
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Network/TrustTokenParamsRefreshPolicyValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Network
  summary: Enumerated member for the Refresh value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "Refresh")]

      Refresh = 1
    return:
      type: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
    content.vb: >-
      <EnumMember(Value:="Refresh")>

      Refresh = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: Refresh
references:
- uid: OpenQA.Selenium.DevTools.V133.Network
  commentId: N:OpenQA.Selenium.DevTools.V133.Network
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V133.Network
  nameWithType: OpenQA.Selenium.DevTools.V133.Network
  fullName: OpenQA.Selenium.DevTools.V133.Network
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Network
    name: Network
    href: OpenQA.Selenium.DevTools.V133.Network.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Network
    name: Network
    href: OpenQA.Selenium.DevTools.V133.Network.html
- uid: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
  parent: OpenQA.Selenium.DevTools.V133.Network
  href: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues.html
  name: TrustTokenParamsRefreshPolicyValues
  nameWithType: TrustTokenParamsRefreshPolicyValues
  fullName: OpenQA.Selenium.DevTools.V133.Network.TrustTokenParamsRefreshPolicyValues
