### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  id: BreakLocationTypeValues
  parent: OpenQA.Selenium.DevTools.V133.Debugger
  children:
  - OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Call
  - OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.DebuggerStatement
  - OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Return
  langs:
  - csharp
  - vb
  name: BreakLocationTypeValues
  nameWithType: BreakLocationTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: BreakLocationTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated values for Debugger.BreakLocation.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<BreakLocationTypeValues>))]

      public enum BreakLocationTypeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of BreakLocationTypeValues)))>

      Public Enum BreakLocationTypeValues
- uid: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.DebuggerStatement
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.DebuggerStatement
  id: DebuggerStatement
  parent: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  langs:
  - csharp
  - vb
  name: DebuggerStatement
  nameWithType: BreakLocationTypeValues.DebuggerStatement
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.DebuggerStatement
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: DebuggerStatement
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the debuggerStatement value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "debuggerStatement")]

      DebuggerStatement = 0
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
    content.vb: >-
      <EnumMember(Value:="debuggerStatement")>

      DebuggerStatement = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: debuggerStatement
- uid: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Call
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Call
  id: Call
  parent: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  langs:
  - csharp
  - vb
  name: Call
  nameWithType: BreakLocationTypeValues.Call
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Call
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Call
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the call value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "call")]

      Call = 1
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
    content.vb: >-
      <EnumMember(Value:="call")>

      Call = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: call
- uid: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Return
  commentId: F:OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Return
  id: Return
  parent: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  langs:
  - csharp
  - vb
  name: Return
  nameWithType: BreakLocationTypeValues.Return
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.Return
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Return
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v133/Debugger/BreakLocationTypeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V133.Debugger
  summary: Enumerated member for the return value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "return")]

      Return = 2
    return:
      type: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
    content.vb: >-
      <EnumMember(Value:="return")>

      Return = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: return
references:
- uid: OpenQA.Selenium.DevTools.V133.Debugger
  commentId: N:OpenQA.Selenium.DevTools.V133.Debugger
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V133.Debugger
  nameWithType: OpenQA.Selenium.DevTools.V133.Debugger
  fullName: OpenQA.Selenium.DevTools.V133.Debugger
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Debugger
    name: Debugger
    href: OpenQA.Selenium.DevTools.V133.Debugger.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133
    name: V133
    href: OpenQA.Selenium.DevTools.V133.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V133.Debugger
    name: Debugger
    href: OpenQA.Selenium.DevTools.V133.Debugger.html
- uid: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
  parent: OpenQA.Selenium.DevTools.V133.Debugger
  href: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues.html
  name: BreakLocationTypeValues
  nameWithType: BreakLocationTypeValues
  fullName: OpenQA.Selenium.DevTools.V133.Debugger.BreakLocationTypeValues
