### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V134.Security
  commentId: N:OpenQA.Selenium.DevTools.V134.Security
  id: Security
  parent: OpenQA.Selenium.DevTools.V134
  children:
  - OpenQA.Selenium.DevTools.V134.Security.CertificateErrorAction
  - OpenQA.Selenium.DevTools.V134.Security.CertificateErrorEventArgs
  - OpenQA.Selenium.DevTools.V134.Security.CertificateSecurityState
  - OpenQA.Selenium.DevTools.V134.Security.DisableCommandResponse
  - OpenQA.Selenium.DevTools.V134.Security.DisableCommandSettings
  - OpenQA.Selenium.DevTools.V134.Security.EnableCommandResponse
  - OpenQA.Selenium.DevTools.V134.Security.EnableCommandSettings
  - OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandResponse
  - OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandSettings
  - OpenQA.Selenium.DevTools.V134.Security.InsecureContentStatus
  - OpenQA.Selenium.DevTools.V134.Security.MixedContentType
  - OpenQA.Selenium.DevTools.V134.Security.SafetyTipInfo
  - OpenQA.Selenium.DevTools.V134.Security.SafetyTipStatus
  - OpenQA.Selenium.DevTools.V134.Security.SecurityAdapter
  - OpenQA.Selenium.DevTools.V134.Security.SecurityState
  - OpenQA.Selenium.DevTools.V134.Security.SecurityStateChangedEventArgs
  - OpenQA.Selenium.DevTools.V134.Security.SecurityStateExplanation
  - OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandResponse
  - OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandSettings
  - OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandResponse
  - OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandSettings
  - OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityState
  - OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityStateChangedEventArgs
  langs:
  - csharp
  - vb
  name: OpenQA.Selenium.DevTools.V134.Security
  nameWithType: OpenQA.Selenium.DevTools.V134.Security
  fullName: OpenQA.Selenium.DevTools.V134.Security
  type: Namespace
  assemblies:
  - WebDriver
references:
- uid: OpenQA.Selenium.DevTools.V134.Security.CertificateErrorAction
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.CertificateErrorAction
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.CertificateErrorAction.html
  name: CertificateErrorAction
  nameWithType: CertificateErrorAction
  fullName: OpenQA.Selenium.DevTools.V134.Security.CertificateErrorAction
- uid: OpenQA.Selenium.DevTools.V134.Security.CertificateErrorEventArgs
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.CertificateErrorEventArgs
  href: OpenQA.Selenium.DevTools.V134.Security.CertificateErrorEventArgs.html
  name: CertificateErrorEventArgs
  nameWithType: CertificateErrorEventArgs
  fullName: OpenQA.Selenium.DevTools.V134.Security.CertificateErrorEventArgs
- uid: OpenQA.Selenium.DevTools.V134.Security.CertificateSecurityState
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.CertificateSecurityState
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.CertificateSecurityState.html
  name: CertificateSecurityState
  nameWithType: CertificateSecurityState
  fullName: OpenQA.Selenium.DevTools.V134.Security.CertificateSecurityState
- uid: OpenQA.Selenium.DevTools.V134.Security.DisableCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.DisableCommandResponse
  href: OpenQA.Selenium.DevTools.V134.Security.DisableCommandResponse.html
  name: DisableCommandResponse
  nameWithType: DisableCommandResponse
  fullName: OpenQA.Selenium.DevTools.V134.Security.DisableCommandResponse
- uid: OpenQA.Selenium.DevTools.V134.Security.DisableCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.DisableCommandSettings
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.DisableCommandSettings.html
  name: DisableCommandSettings
  nameWithType: DisableCommandSettings
  fullName: OpenQA.Selenium.DevTools.V134.Security.DisableCommandSettings
- uid: OpenQA.Selenium.DevTools.V134.Security.EnableCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.EnableCommandResponse
  href: OpenQA.Selenium.DevTools.V134.Security.EnableCommandResponse.html
  name: EnableCommandResponse
  nameWithType: EnableCommandResponse
  fullName: OpenQA.Selenium.DevTools.V134.Security.EnableCommandResponse
- uid: OpenQA.Selenium.DevTools.V134.Security.EnableCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.EnableCommandSettings
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.EnableCommandSettings.html
  name: EnableCommandSettings
  nameWithType: EnableCommandSettings
  fullName: OpenQA.Selenium.DevTools.V134.Security.EnableCommandSettings
- uid: OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandResponse
  href: OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandResponse.html
  name: HandleCertificateErrorCommandResponse
  nameWithType: HandleCertificateErrorCommandResponse
  fullName: OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandResponse
- uid: OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandSettings
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandSettings.html
  name: HandleCertificateErrorCommandSettings
  nameWithType: HandleCertificateErrorCommandSettings
  fullName: OpenQA.Selenium.DevTools.V134.Security.HandleCertificateErrorCommandSettings
- uid: OpenQA.Selenium.DevTools.V134.Security.InsecureContentStatus
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.InsecureContentStatus
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.InsecureContentStatus.html
  name: InsecureContentStatus
  nameWithType: InsecureContentStatus
  fullName: OpenQA.Selenium.DevTools.V134.Security.InsecureContentStatus
- uid: OpenQA.Selenium.DevTools.V134.Security.MixedContentType
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.MixedContentType
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.MixedContentType.html
  name: MixedContentType
  nameWithType: MixedContentType
  fullName: OpenQA.Selenium.DevTools.V134.Security.MixedContentType
- uid: OpenQA.Selenium.DevTools.V134.Security.SafetyTipInfo
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SafetyTipInfo
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.SafetyTipInfo.html
  name: SafetyTipInfo
  nameWithType: SafetyTipInfo
  fullName: OpenQA.Selenium.DevTools.V134.Security.SafetyTipInfo
- uid: OpenQA.Selenium.DevTools.V134.Security.SafetyTipStatus
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SafetyTipStatus
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.SafetyTipStatus.html
  name: SafetyTipStatus
  nameWithType: SafetyTipStatus
  fullName: OpenQA.Selenium.DevTools.V134.Security.SafetyTipStatus
- uid: OpenQA.Selenium.DevTools.V134.Security.SecurityAdapter
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SecurityAdapter
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.SecurityAdapter.html
  name: SecurityAdapter
  nameWithType: SecurityAdapter
  fullName: OpenQA.Selenium.DevTools.V134.Security.SecurityAdapter
- uid: OpenQA.Selenium.DevTools.V134.Security.SecurityState
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SecurityState
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.SecurityState.html
  name: SecurityState
  nameWithType: SecurityState
  fullName: OpenQA.Selenium.DevTools.V134.Security.SecurityState
- uid: OpenQA.Selenium.DevTools.V134.Security.SecurityStateChangedEventArgs
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SecurityStateChangedEventArgs
  href: OpenQA.Selenium.DevTools.V134.Security.SecurityStateChangedEventArgs.html
  name: SecurityStateChangedEventArgs
  nameWithType: SecurityStateChangedEventArgs
  fullName: OpenQA.Selenium.DevTools.V134.Security.SecurityStateChangedEventArgs
- uid: OpenQA.Selenium.DevTools.V134.Security.SecurityStateExplanation
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SecurityStateExplanation
  href: OpenQA.Selenium.DevTools.V134.Security.SecurityStateExplanation.html
  name: SecurityStateExplanation
  nameWithType: SecurityStateExplanation
  fullName: OpenQA.Selenium.DevTools.V134.Security.SecurityStateExplanation
- uid: OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandResponse
  href: OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandResponse.html
  name: SetIgnoreCertificateErrorsCommandResponse
  nameWithType: SetIgnoreCertificateErrorsCommandResponse
  fullName: OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandResponse
- uid: OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandSettings
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandSettings.html
  name: SetIgnoreCertificateErrorsCommandSettings
  nameWithType: SetIgnoreCertificateErrorsCommandSettings
  fullName: OpenQA.Selenium.DevTools.V134.Security.SetIgnoreCertificateErrorsCommandSettings
- uid: OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandResponse
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandResponse
  href: OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandResponse.html
  name: SetOverrideCertificateErrorsCommandResponse
  nameWithType: SetOverrideCertificateErrorsCommandResponse
  fullName: OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandResponse
- uid: OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandSettings
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandSettings
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandSettings.html
  name: SetOverrideCertificateErrorsCommandSettings
  nameWithType: SetOverrideCertificateErrorsCommandSettings
  fullName: OpenQA.Selenium.DevTools.V134.Security.SetOverrideCertificateErrorsCommandSettings
- uid: OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityState
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityState
  parent: OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityState.html
  name: VisibleSecurityState
  nameWithType: VisibleSecurityState
  fullName: OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityState
- uid: OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityStateChangedEventArgs
  commentId: T:OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityStateChangedEventArgs
  href: OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityStateChangedEventArgs.html
  name: VisibleSecurityStateChangedEventArgs
  nameWithType: VisibleSecurityStateChangedEventArgs
  fullName: OpenQA.Selenium.DevTools.V134.Security.VisibleSecurityStateChangedEventArgs
- uid: OpenQA.Selenium.DevTools.V134.Security
  commentId: N:OpenQA.Selenium.DevTools.V134.Security
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V134.Security
  nameWithType: OpenQA.Selenium.DevTools.V134.Security
  fullName: OpenQA.Selenium.DevTools.V134.Security
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134
    name: V134
    href: OpenQA.Selenium.DevTools.V134.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134.Security
    name: Security
    href: OpenQA.Selenium.DevTools.V134.Security.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134
    name: V134
    href: OpenQA.Selenium.DevTools.V134.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134.Security
    name: Security
    href: OpenQA.Selenium.DevTools.V134.Security.html
