### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  id: KeyPathTypeValues
  parent: OpenQA.Selenium.DevTools.V132.IndexedDB
  children:
  - OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Array
  - OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Null
  - OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.String
  langs:
  - csharp
  - vb
  name: KeyPathTypeValues
  nameWithType: KeyPathTypeValues
  fullName: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: KeyPathTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.IndexedDB
  summary: Enumerated values for IndexedDB.KeyPath.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<KeyPathTypeValues>))]

      public enum KeyPathTypeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of KeyPathTypeValues)))>

      Public Enum KeyPathTypeValues
- uid: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Null
  commentId: F:OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Null
  id: "Null"
  parent: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  langs:
  - csharp
  - vb
  name: "Null"
  nameWithType: KeyPathTypeValues.Null
  fullName: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Null
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: "Null"
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.IndexedDB
  summary: Enumerated member for the null value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "null")]

      Null = 0
    return:
      type: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
    content.vb: >-
      <EnumMember(Value:="null")>

      Null = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: "null"
- uid: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.String
  commentId: F:OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.String
  id: String
  parent: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  langs:
  - csharp
  - vb
  name: String
  nameWithType: KeyPathTypeValues.String
  fullName: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.String
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: String
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.IndexedDB
  summary: Enumerated member for the string value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "string")]

      String = 1
    return:
      type: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
    content.vb: >-
      <EnumMember(Value:="string")>

      String = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: string
- uid: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Array
  commentId: F:OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Array
  id: Array
  parent: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  langs:
  - csharp
  - vb
  name: Array
  nameWithType: KeyPathTypeValues.Array
  fullName: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.Array
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Array
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/IndexedDB/KeyPathTypeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.IndexedDB
  summary: Enumerated member for the array value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "array")]

      Array = 2
    return:
      type: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
    content.vb: >-
      <EnumMember(Value:="array")>

      Array = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: array
references:
- uid: OpenQA.Selenium.DevTools.V132.IndexedDB
  commentId: N:OpenQA.Selenium.DevTools.V132.IndexedDB
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V132.IndexedDB
  nameWithType: OpenQA.Selenium.DevTools.V132.IndexedDB
  fullName: OpenQA.Selenium.DevTools.V132.IndexedDB
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.IndexedDB
    name: IndexedDB
    href: OpenQA.Selenium.DevTools.V132.IndexedDB.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.IndexedDB
    name: IndexedDB
    href: OpenQA.Selenium.DevTools.V132.IndexedDB.html
- uid: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
  parent: OpenQA.Selenium.DevTools.V132.IndexedDB
  href: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues.html
  name: KeyPathTypeValues
  nameWithType: KeyPathTypeValues
  fullName: OpenQA.Selenium.DevTools.V132.IndexedDB.KeyPathTypeValues
