### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  commentId: T:OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  id: TraceConfigRecordModeValues
  parent: OpenQA.Selenium.DevTools.V132.Tracing
  children:
  - OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.EchoToConsole
  - OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordAsMuchAsPossible
  - OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordContinuously
  - OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordUntilFull
  langs:
  - csharp
  - vb
  name: TraceConfigRecordModeValues
  nameWithType: TraceConfigRecordModeValues
  fullName: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: TraceConfigRecordModeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Tracing
  summary: Enumerated values for Tracing.TraceConfig.recordMode
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<TraceConfigRecordModeValues>))]

      public enum TraceConfigRecordModeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of TraceConfigRecordModeValues)))>

      Public Enum TraceConfigRecordModeValues
- uid: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordUntilFull
  commentId: F:OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordUntilFull
  id: RecordUntilFull
  parent: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  langs:
  - csharp
  - vb
  name: RecordUntilFull
  nameWithType: TraceConfigRecordModeValues.RecordUntilFull
  fullName: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordUntilFull
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: RecordUntilFull
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Tracing
  summary: Enumerated member for the recordUntilFull value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "recordUntilFull")]

      RecordUntilFull = 0
    return:
      type: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
    content.vb: >-
      <EnumMember(Value:="recordUntilFull")>

      RecordUntilFull = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: recordUntilFull
- uid: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordContinuously
  commentId: F:OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordContinuously
  id: RecordContinuously
  parent: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  langs:
  - csharp
  - vb
  name: RecordContinuously
  nameWithType: TraceConfigRecordModeValues.RecordContinuously
  fullName: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordContinuously
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: RecordContinuously
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Tracing
  summary: Enumerated member for the recordContinuously value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "recordContinuously")]

      RecordContinuously = 1
    return:
      type: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
    content.vb: >-
      <EnumMember(Value:="recordContinuously")>

      RecordContinuously = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: recordContinuously
- uid: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordAsMuchAsPossible
  commentId: F:OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordAsMuchAsPossible
  id: RecordAsMuchAsPossible
  parent: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  langs:
  - csharp
  - vb
  name: RecordAsMuchAsPossible
  nameWithType: TraceConfigRecordModeValues.RecordAsMuchAsPossible
  fullName: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.RecordAsMuchAsPossible
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: RecordAsMuchAsPossible
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Tracing
  summary: Enumerated member for the recordAsMuchAsPossible value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "recordAsMuchAsPossible")]

      RecordAsMuchAsPossible = 2
    return:
      type: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
    content.vb: >-
      <EnumMember(Value:="recordAsMuchAsPossible")>

      RecordAsMuchAsPossible = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: recordAsMuchAsPossible
- uid: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.EchoToConsole
  commentId: F:OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.EchoToConsole
  id: EchoToConsole
  parent: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  langs:
  - csharp
  - vb
  name: EchoToConsole
  nameWithType: TraceConfigRecordModeValues.EchoToConsole
  fullName: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.EchoToConsole
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: EchoToConsole
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Tracing/TraceConfigRecordModeValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Tracing
  summary: Enumerated member for the echoToConsole value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "echoToConsole")]

      EchoToConsole = 3
    return:
      type: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
    content.vb: >-
      <EnumMember(Value:="echoToConsole")>

      EchoToConsole = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: echoToConsole
references:
- uid: OpenQA.Selenium.DevTools.V132.Tracing
  commentId: N:OpenQA.Selenium.DevTools.V132.Tracing
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V132.Tracing
  nameWithType: OpenQA.Selenium.DevTools.V132.Tracing
  fullName: OpenQA.Selenium.DevTools.V132.Tracing
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Tracing
    name: Tracing
    href: OpenQA.Selenium.DevTools.V132.Tracing.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Tracing
    name: Tracing
    href: OpenQA.Selenium.DevTools.V132.Tracing.html
- uid: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  commentId: T:OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
  parent: OpenQA.Selenium.DevTools.V132.Tracing
  href: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues.html
  name: TraceConfigRecordModeValues
  nameWithType: TraceConfigRecordModeValues
  fullName: OpenQA.Selenium.DevTools.V132.Tracing.TraceConfigRecordModeValues
