### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  id: ScreenOrientationTypeValues
  parent: OpenQA.Selenium.DevTools.V134.Emulation
  children:
  - OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapePrimary
  - OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapeSecondary
  - OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitPrimary
  - OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitSecondary
  langs:
  - csharp
  - vb
  name: ScreenOrientationTypeValues
  nameWithType: ScreenOrientationTypeValues
  fullName: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ScreenOrientationTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Emulation
  summary: Enumerated values for Emulation.ScreenOrientation.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<ScreenOrientationTypeValues>))]

      public enum ScreenOrientationTypeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of ScreenOrientationTypeValues)))>

      Public Enum ScreenOrientationTypeValues
- uid: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitPrimary
  commentId: F:OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitPrimary
  id: PortraitPrimary
  parent: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  langs:
  - csharp
  - vb
  name: PortraitPrimary
  nameWithType: ScreenOrientationTypeValues.PortraitPrimary
  fullName: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitPrimary
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: PortraitPrimary
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Emulation
  summary: Enumerated member for the portraitPrimary value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "portraitPrimary")]

      PortraitPrimary = 0
    return:
      type: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
    content.vb: >-
      <EnumMember(Value:="portraitPrimary")>

      PortraitPrimary = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: portraitPrimary
- uid: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitSecondary
  commentId: F:OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitSecondary
  id: PortraitSecondary
  parent: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  langs:
  - csharp
  - vb
  name: PortraitSecondary
  nameWithType: ScreenOrientationTypeValues.PortraitSecondary
  fullName: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.PortraitSecondary
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: PortraitSecondary
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Emulation
  summary: Enumerated member for the portraitSecondary value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "portraitSecondary")]

      PortraitSecondary = 1
    return:
      type: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
    content.vb: >-
      <EnumMember(Value:="portraitSecondary")>

      PortraitSecondary = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: portraitSecondary
- uid: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapePrimary
  commentId: F:OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapePrimary
  id: LandscapePrimary
  parent: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  langs:
  - csharp
  - vb
  name: LandscapePrimary
  nameWithType: ScreenOrientationTypeValues.LandscapePrimary
  fullName: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapePrimary
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: LandscapePrimary
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Emulation
  summary: Enumerated member for the landscapePrimary value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "landscapePrimary")]

      LandscapePrimary = 2
    return:
      type: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
    content.vb: >-
      <EnumMember(Value:="landscapePrimary")>

      LandscapePrimary = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: landscapePrimary
- uid: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapeSecondary
  commentId: F:OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapeSecondary
  id: LandscapeSecondary
  parent: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  langs:
  - csharp
  - vb
  name: LandscapeSecondary
  nameWithType: ScreenOrientationTypeValues.LandscapeSecondary
  fullName: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.LandscapeSecondary
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: LandscapeSecondary
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v134/Emulation/ScreenOrientationTypeValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V134.Emulation
  summary: Enumerated member for the landscapeSecondary value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "landscapeSecondary")]

      LandscapeSecondary = 3
    return:
      type: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
    content.vb: >-
      <EnumMember(Value:="landscapeSecondary")>

      LandscapeSecondary = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: landscapeSecondary
references:
- uid: OpenQA.Selenium.DevTools.V134.Emulation
  commentId: N:OpenQA.Selenium.DevTools.V134.Emulation
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V134.Emulation
  nameWithType: OpenQA.Selenium.DevTools.V134.Emulation
  fullName: OpenQA.Selenium.DevTools.V134.Emulation
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134
    name: V134
    href: OpenQA.Selenium.DevTools.V134.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134.Emulation
    name: Emulation
    href: OpenQA.Selenium.DevTools.V134.Emulation.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134
    name: V134
    href: OpenQA.Selenium.DevTools.V134.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V134.Emulation
    name: Emulation
    href: OpenQA.Selenium.DevTools.V134.Emulation.html
- uid: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
  parent: OpenQA.Selenium.DevTools.V134.Emulation
  href: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues.html
  name: ScreenOrientationTypeValues
  nameWithType: ScreenOrientationTypeValues
  fullName: OpenQA.Selenium.DevTools.V134.Emulation.ScreenOrientationTypeValues
