### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  id: ObjectPreviewTypeValues
  parent: OpenQA.Selenium.DevTools.V132.Runtime
  children:
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Bigint
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Boolean
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Function
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Number
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Object
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.String
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Symbol
  - OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Undefined
  langs:
  - csharp
  - vb
  name: ObjectPreviewTypeValues
  nameWithType: ObjectPreviewTypeValues
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: ObjectPreviewTypeValues
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated values for Runtime.ObjectPreview.type
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<ObjectPreviewTypeValues>))]

      public enum ObjectPreviewTypeValues
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of ObjectPreviewTypeValues)))>

      Public Enum ObjectPreviewTypeValues
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Object
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Object
  id: Object
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: Object
  nameWithType: ObjectPreviewTypeValues.Object
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Object
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Object
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the object value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "object")]

      Object = 0
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="object")>

      Object = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: object
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Function
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Function
  id: Function
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: Function
  nameWithType: ObjectPreviewTypeValues.Function
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Function
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Function
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the function value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "function")]

      Function = 1
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="function")>

      Function = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: function
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Undefined
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Undefined
  id: Undefined
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: Undefined
  nameWithType: ObjectPreviewTypeValues.Undefined
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Undefined
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Undefined
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the undefined value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "undefined")]

      Undefined = 2
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="undefined")>

      Undefined = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: undefined
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.String
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.String
  id: String
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: String
  nameWithType: ObjectPreviewTypeValues.String
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.String
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: String
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the string value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "string")]

      String = 3
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="string")>

      String = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: string
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Number
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Number
  id: Number
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: Number
  nameWithType: ObjectPreviewTypeValues.Number
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Number
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Number
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 38
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the number value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "number")]

      Number = 4
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="number")>

      Number = 4
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: number
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Boolean
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Boolean
  id: Boolean
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: Boolean
  nameWithType: ObjectPreviewTypeValues.Boolean
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Boolean
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Boolean
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 43
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the boolean value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "boolean")]

      Boolean = 5
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="boolean")>

      Boolean = 5
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: boolean
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Symbol
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Symbol
  id: Symbol
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: Symbol
  nameWithType: ObjectPreviewTypeValues.Symbol
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Symbol
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Symbol
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 48
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the symbol value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "symbol")]

      Symbol = 6
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="symbol")>

      Symbol = 6
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: symbol
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Bigint
  commentId: F:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Bigint
  id: Bigint
  parent: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  langs:
  - csharp
  - vb
  name: Bigint
  nameWithType: ObjectPreviewTypeValues.Bigint
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.Bigint
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Bigint
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Runtime/ObjectPreviewTypeValues.cs
    startLine: 53
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Runtime
  summary: Enumerated member for the bigint value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "bigint")]

      Bigint = 7
    return:
      type: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
    content.vb: >-
      <EnumMember(Value:="bigint")>

      Bigint = 7
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: bigint
references:
- uid: OpenQA.Selenium.DevTools.V132.Runtime
  commentId: N:OpenQA.Selenium.DevTools.V132.Runtime
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V132.Runtime
  nameWithType: OpenQA.Selenium.DevTools.V132.Runtime
  fullName: OpenQA.Selenium.DevTools.V132.Runtime
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Runtime
    name: Runtime
    href: OpenQA.Selenium.DevTools.V132.Runtime.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Runtime
    name: Runtime
    href: OpenQA.Selenium.DevTools.V132.Runtime.html
- uid: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  commentId: T:OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
  parent: OpenQA.Selenium.DevTools.V132.Runtime
  href: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues.html
  name: ObjectPreviewTypeValues
  nameWithType: ObjectPreviewTypeValues
  fullName: OpenQA.Selenium.DevTools.V132.Runtime.ObjectPreviewTypeValues
