### YamlMime:ManagedReference
items:
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  commentId: T:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  id: AXValueSourceType
  parent: OpenQA.Selenium.DevTools.V132.Accessibility
  children:
  - OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Attribute
  - OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Contents
  - OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Implicit
  - OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Placeholder
  - OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.RelatedElement
  - OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Style
  langs:
  - csharp
  - vb
  name: AXValueSourceType
  nameWithType: AXValueSourceType
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  type: Enum
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: AXValueSourceType
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
    startLine: 12
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Accessibility
  summary: AXValueSourceType
  example: []
  syntax:
    content: >-
      [JsonConverter(typeof(JsonEnumMemberConverter<AXValueSourceType>))]

      public enum AXValueSourceType
    content.vb: >-
      <JsonConverter(GetType(JsonEnumMemberConverter(Of AXValueSourceType)))>

      Public Enum AXValueSourceType
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Attribute
  commentId: F:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Attribute
  id: Attribute
  parent: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  langs:
  - csharp
  - vb
  name: Attribute
  nameWithType: AXValueSourceType.Attribute
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Attribute
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Attribute
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
    startLine: 18
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Accessibility
  summary: Enumerated member for the attribute value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "attribute")]

      Attribute = 0
    return:
      type: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
    content.vb: >-
      <EnumMember(Value:="attribute")>

      Attribute = 0
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: attribute
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Implicit
  commentId: F:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Implicit
  id: Implicit
  parent: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  langs:
  - csharp
  - vb
  name: Implicit
  nameWithType: AXValueSourceType.Implicit
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Implicit
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Implicit
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
    startLine: 23
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Accessibility
  summary: Enumerated member for the implicit value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "implicit")]

      Implicit = 1
    return:
      type: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
    content.vb: >-
      <EnumMember(Value:="implicit")>

      Implicit = 1
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: implicit
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Style
  commentId: F:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Style
  id: Style
  parent: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  langs:
  - csharp
  - vb
  name: Style
  nameWithType: AXValueSourceType.Style
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Style
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Style
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
    startLine: 28
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Accessibility
  summary: Enumerated member for the style value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "style")]

      Style = 2
    return:
      type: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
    content.vb: >-
      <EnumMember(Value:="style")>

      Style = 2
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: style
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Contents
  commentId: F:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Contents
  id: Contents
  parent: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  langs:
  - csharp
  - vb
  name: Contents
  nameWithType: AXValueSourceType.Contents
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Contents
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Contents
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
    startLine: 33
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Accessibility
  summary: Enumerated member for the contents value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "contents")]

      Contents = 3
    return:
      type: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
    content.vb: >-
      <EnumMember(Value:="contents")>

      Contents = 3
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: contents
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Placeholder
  commentId: F:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Placeholder
  id: Placeholder
  parent: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  langs:
  - csharp
  - vb
  name: Placeholder
  nameWithType: AXValueSourceType.Placeholder
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.Placeholder
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: Placeholder
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
    startLine: 38
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Accessibility
  summary: Enumerated member for the placeholder value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "placeholder")]

      Placeholder = 4
    return:
      type: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
    content.vb: >-
      <EnumMember(Value:="placeholder")>

      Placeholder = 4
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: placeholder
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.RelatedElement
  commentId: F:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.RelatedElement
  id: RelatedElement
  parent: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  langs:
  - csharp
  - vb
  name: RelatedElement
  nameWithType: AXValueSourceType.RelatedElement
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.RelatedElement
  type: Field
  source:
    remote:
      path: bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
      branch: trunk
      repo: https://github.com/SeleniumHQ/selenium
    id: RelatedElement
    path: ../../bazel-bin/dotnet/src/webdriver/cdp/v132/Accessibility/AXValueSourceType.cs
    startLine: 43
  assemblies:
  - WebDriver
  namespace: OpenQA.Selenium.DevTools.V132.Accessibility
  summary: Enumerated member for the relatedElement value.
  example: []
  syntax:
    content: >-
      [EnumMember(Value = "relatedElement")]

      RelatedElement = 5
    return:
      type: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
    content.vb: >-
      <EnumMember(Value:="relatedElement")>

      RelatedElement = 5
  attributes:
  - type: System.Runtime.Serialization.EnumMemberAttribute
    ctor: System.Runtime.Serialization.EnumMemberAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Value
      type: System.String
      value: relatedElement
references:
- uid: OpenQA.Selenium.DevTools.V132.Accessibility
  commentId: N:OpenQA.Selenium.DevTools.V132.Accessibility
  href: OpenQA.html
  name: OpenQA.Selenium.DevTools.V132.Accessibility
  nameWithType: OpenQA.Selenium.DevTools.V132.Accessibility
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility
  spec.csharp:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Accessibility
    name: Accessibility
    href: OpenQA.Selenium.DevTools.V132.Accessibility.html
  spec.vb:
  - uid: OpenQA
    name: OpenQA
    href: OpenQA.html
  - name: .
  - uid: OpenQA.Selenium
    name: Selenium
    href: OpenQA.Selenium.html
  - name: .
  - uid: OpenQA.Selenium.DevTools
    name: DevTools
    href: OpenQA.Selenium.DevTools.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132
    name: V132
    href: OpenQA.Selenium.DevTools.V132.html
  - name: .
  - uid: OpenQA.Selenium.DevTools.V132.Accessibility
    name: Accessibility
    href: OpenQA.Selenium.DevTools.V132.Accessibility.html
- uid: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  commentId: T:OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
  parent: OpenQA.Selenium.DevTools.V132.Accessibility
  href: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType.html
  name: AXValueSourceType
  nameWithType: AXValueSourceType
  fullName: OpenQA.Selenium.DevTools.V132.Accessibility.AXValueSourceType
